function createfigure(cdata1, cdata2, YData1, XData1, XData2, YData2, XData3, YData3, XData4, XData5, YData4, YData5)
%CREATEFIGURE(cdata1, cdata2, YData1, XData1, XData2, YData2, XData3, YData3, XData4, XData5, YData4, YData5)
%  CDATA1:  image cdata
%  CDATA2:  image cdata
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  XDATA4:  line xdata
%  XDATA5:  line xdata
%  YDATA4:  line ydata
%  YDATA5:  line ydata

%  Auto-generated by MATLAB on 09-Mar-2025 12:54:53

% Create figure
figure('InvertHardcopy','off','PaperUnits','normalized','PaperType','A4',...
    'Tag','Graphics',...
    'NumberTitle','off',...
    'Name','SPM12 (7771): Graphics',...
    'Color',[1 1 1]);
colormap(gray(64));

% Create axes
axes1 = axes('Tag','hMIPax','Position',[0.05 0.6 0.55 0.36]);
axis off
hold(axes1,'on');

% Create image
image(cdata1);

% Create text
text('Tag','hMIPxyz','VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontName','Times New Roman',...
    'Rotation',90,...
    'String',{'{\bfSPM}{\itmip}','[0, 0, 0]'},...
    'Position',[0 182.25 0],...
    'Color',[0.7 0.7 0.7],...
    'Visible','on');

% Create text
text('Tag','hX1r','FontSize',16,'String','<','Position',[125 275 0],...
    'Color',[1 0 0],...
    'Visible','on');

% Create text
text('Tag','hX2r','FontSize',16,'String','<','Position',[125 111 0],...
    'Color',[1 0 0],...
    'Visible','on');

% Create text
text('Tag','hX3r','FontSize',16,'String','<','Position',[307 111 0],...
    'Color',[1 0 0],...
    'Visible','on');

% Create text
text('FontWeight','bold','FontSize',13,'String','SPM\{T_{452}\}',...
    'Position',[240 260 0],...
    'Visible','on');

box(axes1,'on');
axis(axes1,'tight');
axis(axes1,'ij');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'Layer','top');
% Create axes
axes('Position',[0.02 0.96 0.96 0.04]);
axis off

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',13,...
    'String','IncFH - IncSH - All Sessions',...
    'Position',[0.5 0.5 0],...
    'Visible','on');

% Create axes
axes2 = axes('Tag','PermRes','Position',[20.325 322.575 182.925 29.325],...
    'Units','points');
axis off

% Create text
text('FontWeight','bold','FontSize',13,'String','SPMresults:',...
    'Position',[0 24 0],...
    'Visible','on');

% Create text
text('String','.\BIDS\sub-01\1stLevel','Position',[0.340163924288555 24 0],...
    'Visible','on');

% Create text
text('String','Height threshold T = 3.108360  {p<0.001 (unc.)}',...
    'Position',[0 12 0],...
    'Visible','on');

% Create text
text('String','Extent threshold k = 20 voxels','Position',[0 0 0],...
    'Visible','on');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 29.325]);
% Create axes
axes3 = axes('Position',[0.65 0.55 0.25 0.25]);
hold(axes3,'on');

% Create image
image(cdata2);

% Create xlabel
xlabel('Design matrix','FontName','Arial Narrow');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0.5 13.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0.5 480.5]);
box(axes3,'on');
axis(axes3,'ij');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'Layer','top');
% Create axes
axes('Tag','ConGrphAx','Position',[0.65 0.8075 0.25 0.0675]);
axis off

% Create title
title('contrast');

% Create axes
axes4 = axes('Tag','ConGrphAx','Position',[0.65 0.8075 0.25 0.0675]);

% Create patch
patch('YData',YData1,'XData',XData1,'FaceColor',[0.5 0.5 0.5]);

% Create ylabel
ylabel('1','FontName','Arial Narrow');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0 13]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[-1.1 1.1]);
% Set the remaining axes properties
set(axes4,'TickDir','out','XTick',[0.5 2.5 4.5 6.5 8.5 10.5 12.5],...
    'XTickLabel','','YTick',[-1 0 1],'YTickLabel','');
% Create axes
axes5 = axes('Tag','SPMList','Position',[10.1625 58.65 365.85 234.6],...
    'Units','points');

% Create text
text('FontWeight','bold','FontSize',11,...
    'String','Statistics:  \it\fontsize{9}p-values adjusted for search volume',...
    'Position',[0 225 0]);

% Create line
line(XData2,YData2,'LineWidth',3,'Color',[1 0 0]);

% Create text
text('FontSize',9,'String','set-level','Position',[0.01 210.375 0]);

% Create line
line(XData3,YData3,'Color',[1 0 0]);

% Create text
text('String','\itp','Position',[0.02 200.25 0]);

% Create text
text('String','\itc','Position',[0.08 200.25 0]);

% Create text
text('FontSize',9,'String','cluster-level','Position',[0.22 210.375 0]);

% Create line
line(XData4,YData3,'Color',[1 0 0]);

% Create text
text('String','\itp\rm_{FWE-corr}','Position',[0.15 200.25 0]);

% Create text
text('String','\itq\rm_{FDR-corr}','Position',[0.24 200.25 0]);

% Create text
text('String','\itk\rm_E','Position',[0.34 200.25 0]);

% Create text
text('String','\itp\rm_{uncorr}','Position',[0.39 200.25 0]);

% Create text
text('FontSize',9,'String','peak-level','Position',[0.64 210.375 0]);

% Create line
line(XData5,YData3,'Color',[1 0 0]);

% Create text
text('String','\itp\rm_{FWE-corr}','Position',[0.49 200.25 0]);

% Create text
text('String','\itq\rm_{FDR-corr}','Position',[0.58 200.25 0]);

% Create text
text('String','\itT','Position',[0.67 200.25 0]);

% Create text
text('String','(\itZ\rm_E)','Position',[0.75 200.25 0]);

% Create text
text('String','\itp\rm_{uncorr}','Position',[0.82 200.25 0]);

% Create text
text('FontSize',8,'String','mm mm mm','Position',[0.92 205.875 0]);

% Create line
line(XData2,YData4,'LineWidth',1,'Color',[1 0 0]);

% Create text
text('HorizontalAlignment','center','FontAngle','italic','FontSize',8,...
    'FontName','Arial Narrow',...
    'String','table shows 3 local maxima more than 8.0mm apart',...
    'Position',[0.5 4 0]);

% Create line
line(XData2,YData5,'LineWidth',1,'Color',[1 0 0]);

% Create text
text('String','Height threshold: T = 3.11, p = 0.001 (1.000)',...
    'Position',[0 -9 0]);

% Create text
text('String','Extent threshold: k = 20 voxels, p = 0.175 (0.979)',...
    'Position',[0 -18 0]);

% Create text
text('String','Expected voxels per cluster, <k> = 11.557',...
    'Position',[0 -27 0]);

% Create text
text('String','Expected number of clusters, <c> = 3.88',...
    'Position',[0 -36 0]);

% Create text
text('String','FWEp: 4.917, FDRp: Inf, FWEc: 239, FDRc: 239',...
    'Position',[0 -45 0]);

% Create text
text('String','Degrees of freedom = [1.0, 452.0]','Position',[0.5 -9 0]);

% Create text
text('String','FWHM = 9.4 9.4 8.9 mm mm mm; 4.7 4.7 4.5 {voxels}',...
    'Position',[0.5 -18 0]);

% Create text
text('String','Volume: 1846664 = 230833 voxels = 2168.0 resels',...
    'Position',[0.5 -27 0]);

% Create text
text('String','Voxel size: 2.0 2.0 2.0 mm mm mm; (resel = 99.08 voxels)',...
    'Position',[0.5 -36 0]);

% Create text
text('FontWeight','bold','String','0.542','Position',[0.01 183.375 0]);

% Create text
text('FontWeight','bold','String','4','Position',[0.08 183.375 0]);

% Create text
text('FontWeight','bold','String','0.000','Position',[0.15 183.375 0]);

% Create text
text('FontWeight','bold','String','0.000','Position',[0.24 183.375 0]);

% Create text
text('FontWeight','bold','String','310','Position',[0.33 183.375 0]);

% Create text
text('FontWeight','bold','String','0.000','Position',[0.39 183.375 0]);

% Create text
text('FontWeight','bold','String','0.727','Position',[0.49 183.375 0]);

% Create text
text('FontWeight','bold','String','0.474','Position',[0.58 183.375 0]);

% Create text
text('FontWeight','bold','String','  4.08','Position',[0.65 183.375 0]);

% Create text
text('FontWeight','bold','String',' 4.04','Position',[0.74 183.375 0]);

% Create text
text('FontWeight','bold','String','0.000','Position',[0.83 183.375 0]);

% Create text
text('Tag','ListXYZ','FontWeight','bold','String',' 30  -98  -8',...
    'Position',[0.92 183.375 0]);

% Create text
text('Position',[0.15 174.375 0]);

% Create text
text('Position',[0.24 174.375 0]);

% Create text
text('Position',[0.33 174.375 0]);

% Create text
text('Position',[0.39 174.375 0]);

% Create text
text('String','0.747','Position',[0.49 174.375 0]);

% Create text
text('String','0.474','Position',[0.58 174.375 0]);

% Create text
text('String','  4.06','Position',[0.65 174.375 0]);

% Create text
text('String',' 4.02','Position',[0.74 174.375 0]);

% Create text
text('String','0.000','Position',[0.83 174.375 0]);

% Create text
text('Tag','ListXYZ','String',' 16 -104   4','Position',[0.92 174.375 0]);

% Create text
text('Position',[0.15 165.375 0]);

% Create text
text('Position',[0.24 165.375 0]);

% Create text
text('Position',[0.33 165.375 0]);

% Create text
text('Position',[0.39 165.375 0]);

% Create text
text('String','0.790','Position',[0.49 165.375 0]);

% Create text
text('String','0.474','Position',[0.58 165.375 0]);

% Create text
text('String','  4.02','Position',[0.65 165.375 0]);

% Create text
text('String',' 3.99','Position',[0.74 165.375 0]);

% Create text
text('String','0.000','Position',[0.83 165.375 0]);

% Create text
text('Tag','ListXYZ','String',' 34  -90   2','Position',[0.92 165.375 0]);

% Create text
text('FontWeight','bold','String','0.002','Position',[0.15 156.375 0]);

% Create text
text('FontWeight','bold','String','0.001','Position',[0.24 156.375 0]);

% Create text
text('FontWeight','bold','String','239','Position',[0.33 156.375 0]);

% Create text
text('FontWeight','bold','String','0.000','Position',[0.39 156.375 0]);

% Create text
text('FontWeight','bold','String','0.824','Position',[0.49 156.375 0]);

% Create text
text('FontWeight','bold','String','0.474','Position',[0.58 156.375 0]);

% Create text
text('FontWeight','bold','String','  3.99','Position',[0.65 156.375 0]);

% Create text
text('FontWeight','bold','String',' 3.96','Position',[0.74 156.375 0]);

% Create text
text('FontWeight','bold','String','0.000','Position',[0.83 156.375 0]);

% Create text
text('Tag','ListXYZ','FontWeight','bold','String','-26  -98   2',...
    'Position',[0.92 156.375 0]);

% Create text
text('Position',[0.15 147.375 0]);

% Create text
text('Position',[0.24 147.375 0]);

% Create text
text('Position',[0.33 147.375 0]);

% Create text
text('Position',[0.39 147.375 0]);

% Create text
text('String','0.895','Position',[0.49 147.375 0]);

% Create text
text('String','0.474','Position',[0.58 147.375 0]);

% Create text
text('String','  3.91','Position',[0.65 147.375 0]);

% Create text
text('String',' 3.88','Position',[0.74 147.375 0]);

% Create text
text('String','0.000','Position',[0.83 147.375 0]);

% Create text
text('Tag','ListXYZ','String','-16 -102 -10','Position',[0.92 147.375 0]);

% Create text
text('Position',[0.15 138.375 0]);

% Create text
text('Position',[0.24 138.375 0]);

% Create text
text('Position',[0.33 138.375 0]);

% Create text
text('Position',[0.39 138.375 0]);

% Create text
text('String','1.000','Position',[0.49 138.375 0]);

% Create text
text('String','0.817','Position',[0.58 138.375 0]);

% Create text
text('String','  3.49','Position',[0.65 138.375 0]);

% Create text
text('String',' 3.47','Position',[0.74 138.375 0]);

% Create text
text('String','0.000','Position',[0.83 138.375 0]);

% Create text
text('Tag','ListXYZ','String','-26  -92 -10','Position',[0.92 138.375 0]);

% Create text
text('FontWeight','bold','String','0.955','Position',[0.15 129.375 0]);

% Create text
text('FontWeight','bold','String','0.689','Position',[0.24 129.375 0]);

% Create text
text('FontWeight','bold','String','24','Position',[0.33 129.375 0]);

% Create text
text('FontWeight','bold','String','0.140','Position',[0.39 129.375 0]);

% Create text
text('FontWeight','bold','String','0.995','Position',[0.49 129.375 0]);

% Create text
text('FontWeight','bold','String','0.732','Position',[0.58 129.375 0]);

% Create text
text('FontWeight','bold','String','  3.64','Position',[0.65 129.375 0]);

% Create text
text('FontWeight','bold','String',' 3.62','Position',[0.74 129.375 0]);

% Create text
text('FontWeight','bold','String','0.000','Position',[0.83 129.375 0]);

% Create text
text('Tag','ListXYZ','FontWeight','bold','String',' 14  -94  22',...
    'Position',[0.92 129.375 0]);

% Create text
text('FontWeight','bold','String','0.938','Position',[0.15 120.375 0]);

% Create text
text('FontWeight','bold','String','0.689','Position',[0.24 120.375 0]);

% Create text
text('FontWeight','bold','String','26','Position',[0.33 120.375 0]);

% Create text
text('FontWeight','bold','String','0.125','Position',[0.39 120.375 0]);

% Create text
text('FontWeight','bold','String','0.998','Position',[0.49 120.375 0]);

% Create text
text('FontWeight','bold','String','0.817','Position',[0.58 120.375 0]);

% Create text
text('FontWeight','bold','String','  3.57','Position',[0.65 120.375 0]);

% Create text
text('FontWeight','bold','String',' 3.55','Position',[0.74 120.375 0]);

% Create text
text('FontWeight','bold','String','0.000','Position',[0.83 120.375 0]);

% Create text
text('Tag','ListXYZ','FontWeight','bold','String',' 10   10   6',...
    'Position',[0.92 120.375 0]);

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[0 234.6]);
% Set the remaining axes properties
set(axes5,'ContextMenu','XColor',[1 1 1],'XTick',[],'YColor',[1 1 1],...
    'YTick',[]);
